package id.qsolution.models;

import com.turbomanage.storm.api.Entity;
import com.turbomanage.storm.api.Id;

// Generated Jan 29, 2014 12:26:12 AM by Hibernate Tools 3.4.0.CR1



/**
 * TmBrand generated by hbm2java
 */

@SuppressWarnings("serial")
@Entity
public class TmBrand implements java.io.Serializable {

	@Id
	private long id;
	private String kode = "00";
	private String nama;
	private String kodeCompany;

	public TmBrand() {
	}

	public TmBrand(String kode) {
		this.kode = kode;
	}

	public TmBrand(String kode, String nama, String kodeCompany) {
		this.kode = kode;
		this.nama = nama;
		this.kodeCompany = kodeCompany;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	
	public String getKode() {
		return this.kode;
	}

	public void setKode(String kode) {
		this.kode = kode;
	}

	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

	public String getKodeCompany() {
		return this.kodeCompany;
	}

	public void setKodeCompany(String kodeCompany) {
		this.kodeCompany = kodeCompany;
	}

}
