package id.qsolution.models;

import com.turbomanage.storm.api.Entity;
import com.turbomanage.storm.api.Id;

// Generated Jan 29, 2014 12:26:12 AM by Hibernate Tools 3.4.0.CR1



/**
 * TmFasilitas generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
public class TmFasilitas implements java.io.Serializable {

	@Id
	private long id;
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	private String kode;
	//private TmTipeOutlet tmTipeOutlet;
	private String nama;
	private int urutan;
	private String tipeOutlet;

	public String getTipeOutlet() {
		return tipeOutlet;
	}

	public void setTipeOutlet(String tipeOutlet) {
		this.tipeOutlet = tipeOutlet;
	}

	public TmFasilitas() {
	}

	public TmFasilitas(String kode, int urutan) {
		this.kode = kode;
		this.urutan = urutan;
	}

	public TmFasilitas(String kode, TmTipeOutlet tmTipeOutlet, String nama,
			int urutan) {
		this.kode = kode;
		//this.tmTipeOutlet = tmTipeOutlet;
		this.nama = nama;
		this.urutan = urutan;
	}


	public String getKode() {
		return this.kode;
	}

	public void setKode(String kode) {
		this.kode = kode;
	}

/*	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "kode_tipe_outlet")
	public TmTipeOutlet getTmTipeOutlet() {
		return this.tmTipeOutlet;
	}

	public void setTmTipeOutlet(TmTipeOutlet tmTipeOutlet) {
		this.tmTipeOutlet = tmTipeOutlet;
	}*/

	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

	public int getUrutan() {
		return this.urutan;
	}

	public void setUrutan(int urutan) {
		this.urutan = urutan;
	}

}
