package id.qsolution.models;

import com.turbomanage.storm.api.Entity;
// Generated Jan 29, 2014 12:26:12 AM by Hibernate Tools 3.4.0.CR1
import com.turbomanage.storm.api.Id;


/**
 * TmGroupRak generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
public class TmGroupRak implements java.io.Serializable {

	@Id
	private long id;
	private String kode;
	private String nama;
	private String kodeTypeOutlet;
	private int urutan;
	
	public long getId() {
		return id;
	}
	public void setId(long id) {
		this.id = id;
	}
	public String getKode() {
		return kode;
	}
	public void setKode(String kode) {
		this.kode = kode;
	}
	public String getNama() {
		return nama;
	}
	public void setNama(String nama) {
		this.nama = nama;
	}
	public String getKodeTypeOutlet() {
		return kodeTypeOutlet;
	}
	public void setKodeTypeOutlet(String kodeTypeOutlet) {
		this.kodeTypeOutlet = kodeTypeOutlet;
	}
	public int getUrutan() {
		return urutan;
	}
	public void setUrutan(int urutan) {
		this.urutan = urutan;
	}
}
