package id.qsolution.models;

import com.turbomanage.storm.api.Entity;
import com.turbomanage.storm.api.Id;

// Generated Jan 29, 2014 12:26:12 AM by Hibernate Tools 3.4.0.CR1
/**
 * TmJenisLokasi generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
public class TmJenisLokasi implements java.io.Serializable {

	@Id
	private long id;
	

	private String kode;
	private String nama;

	public TmJenisLokasi() {
	}

	public TmJenisLokasi(String kode) {
		this.kode = kode;
	}

	public TmJenisLokasi(String kode, String nama) {
		this.kode = kode;
		this.nama = nama;
	}
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}
	public String getKode() {
		return this.kode;
	}

	public void setKode(String kode) {
		this.kode = kode;
	}

	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

}
