package id.qsolution.models;

// Generated Jan 29, 2014 12:26:12 AM by Hibernate Tools 3.4.0.CR1
import java.util.Set;
import com.turbomanage.storm.api.Entity;
import com.turbomanage.storm.api.Id;

/**
 * TmKabupaten generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
public class TmKabupaten implements java.io.Serializable {

	@Id
	private long id;
	private String kode;
	//private TmPropinsi tmPropinsi;
	private String nama;
	//private Set<TmKecamatan> tmKecamatans = new HashSet<TmKecamatan>(0);

	public TmKabupaten() {
	}

	public TmKabupaten(String kode) {
		this.kode = kode;
	}

	public TmKabupaten(String kode, TmPropinsi tmPropinsi, String nama,
			Set<TmKecamatan> tmKecamatans) {
		this.kode = kode;
		//this.tmPropinsi = tmPropinsi;
		this.nama = nama;
		//this.tmKecamatans = tmKecamatans;
	}
	
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getKode() {
		return this.kode;
	}

	public void setKode(String kode) {
		this.kode = kode;
	}

	/*@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "kode_prop")
	public TmPropinsi getTmPropinsi() {
		return this.tmPropinsi;
	}

	public void setTmPropinsi(TmPropinsi tmPropinsi) {
		this.tmPropinsi = tmPropinsi;
	}*/

	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "tmKabupaten")
	public Set<TmKecamatan> getTmKecamatans() {
		return this.tmKecamatans;
	}

	public void setTmKecamatans(Set<TmKecamatan> tmKecamatans) {
		this.tmKecamatans = tmKecamatans;
	}
*/
}
