package id.qsolution.models;

// Generated Jan 29, 2014 12:26:12 AM by Hibernate Tools 3.4.0.CR1


import java.util.Set;
import com.turbomanage.storm.api.Entity;
import com.turbomanage.storm.api.Id;

/**
 * TmKategoriBarang generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
public class TmKategoriBarang implements java.io.Serializable {

	@Id
	private long id;
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	private String kode;
	private String nama;
	/*private Set<TmSubKategoriBarang> tmSubKategoriBarangs = new HashSet<TmSubKategoriBarang>(
			0);*/

	public TmKategoriBarang() {
	}

	public TmKategoriBarang(String kode) {
		this.kode = kode;
	}

	public TmKategoriBarang(String kode, String nama,
			Set<TmSubKategoriBarang> tmSubKategoriBarangs) {
		this.kode = kode;
		this.nama = nama;
	//	this.tmSubKategoriBarangs = tmSubKategoriBarangs;
	}


	public String getKode() {
		return this.kode;
	}

	public void setKode(String kode) {
		this.kode = kode;
	}

	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

/*	public Set<TmSubKategoriBarang> getTmSubKategoriBarangs() {
		return this.tmSubKategoriBarangs;
	}

	public void setTmSubKategoriBarangs(
			Set<TmSubKategoriBarang> tmSubKategoriBarangs) {
		this.tmSubKategoriBarangs = tmSubKategoriBarangs;
	}*/

}
