package id.qsolution.models;

import com.turbomanage.storm.api.Entity;
import com.turbomanage.storm.api.Id;

// Generated Jan 29, 2014 12:26:12 AM by Hibernate Tools 3.4.0.CR1



/**
 * TmKecamatan generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
public class TmKecamatan implements java.io.Serializable {

	@Id
	private long id;
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	private String kode;
	//private TmKabupaten tmKabupaten;
	private String nama;

	public TmKecamatan() {
	}

	public TmKecamatan(String kode) {
		this.kode = kode;
	}

	public TmKecamatan(String kode, TmKabupaten tmKabupaten, String nama) {
		this.kode = kode;
		//this.tmKabupaten = tmKabupaten;
		this.nama = nama;
	}

	public String getKode() {
		return this.kode;
	}

	public void setKode(String kode) {
		this.kode = kode;
	}

/*	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "kode_kab")
	public TmKabupaten getTmKabupaten() {
		return this.tmKabupaten;
	}

	public void setTmKabupaten(TmKabupaten tmKabupaten) {
		this.tmKabupaten = tmKabupaten;
	}
*/

	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

}
