package id.qsolution.models;

// Generated Jan 29, 2014 12:26:12 AM by Hibernate Tools 3.4.0.CR1

import java.util.Set;
import com.turbomanage.storm.api.Entity;
import com.turbomanage.storm.api.Id;


/**
 * TmKlasifikasiOutlet generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
public class TmKlasifikasiOutlet implements java.io.Serializable {


	@Id
	private long id;
	private String kode;
	private String nama;
	private String kodeTipe;
	//private Set<TmOutlet> tmOutlets = new HashSet<TmOutlet>(0);

	public TmKlasifikasiOutlet() {
	}

	public TmKlasifikasiOutlet(String kode) {
		this.kode = kode;
	}

	public TmKlasifikasiOutlet(String kode, String nama, String kodeTipe,
			Set<TmOutlet> tmOutlets) {
		this.kode = kode;
		this.nama = nama;
		this.kodeTipe = kodeTipe;
		//this.tmOutlets = tmOutlets;
	}


	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}
	
	public String getKode() {
		return this.kode;
	}

	public void setKode(String kode) {
		this.kode = kode;
	}


	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

	public String getKodeTipe() {
		return this.kodeTipe;
	}

	public void setKodeTipe(String kodeTipe) {
		this.kodeTipe = kodeTipe;
	}

/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tmKlasifikasiOutlet")
	public Set<TmOutlet> getTmOutlets() {
		return this.tmOutlets;
	}

	public void setTmOutlets(Set<TmOutlet> tmOutlets) {
		this.tmOutlets = tmOutlets;
	}*/

}
