package id.qsolution.models;

// Generated Jan 29, 2014 12:26:12 AM by Hibernate Tools 3.4.0.CR1


/**
 * TmLokasi generated by hbm2java
 */
@SuppressWarnings("serial")
public class TmLokasi implements java.io.Serializable {

	private String kode;
	private String nama;

	public TmLokasi() {
	}

	public TmLokasi(String kode) {
		this.kode = kode;
	}

	public TmLokasi(String kode, String nama) {
		this.kode = kode;
		this.nama = nama;
	}

	public String getKode() {
		return this.kode;
	}

	public void setKode(String kode) {
		this.kode = kode;
	}

	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

}
