package id.qsolution.models;

// Generated Jan 29, 2014 12:26:12 AM by Hibernate Tools 3.4.0.CR1
/**
 * TmOutletFasilitasId generated by hbm2java
 */
@SuppressWarnings("serial")
public class TmOutletFasilitasId implements java.io.Serializable {

	private String kodeOutlet;
	private String kodeFasilitas;

	public TmOutletFasilitasId() {
	}

	public TmOutletFasilitasId(String kodeOutlet, String kodeFasilitas) {
		this.kodeOutlet = kodeOutlet;
		this.kodeFasilitas = kodeFasilitas;
	}

	public String getKodeOutlet() {
		return this.kodeOutlet;
	}

	public void setKodeOutlet(String kodeOutlet) {
		this.kodeOutlet = kodeOutlet;
	}

	public String getKodeFasilitas() {
		return this.kodeFasilitas;
	}

	public void setKodeFasilitas(String kodeFasilitas) {
		this.kodeFasilitas = kodeFasilitas;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmOutletFasilitasId))
			return false;
		TmOutletFasilitasId castOther = (TmOutletFasilitasId) other;

		return ((this.getKodeOutlet() == castOther.getKodeOutlet()) || (this
				.getKodeOutlet() != null && castOther.getKodeOutlet() != null && this
				.getKodeOutlet().equals(castOther.getKodeOutlet())))
				&& ((this.getKodeFasilitas() == castOther.getKodeFasilitas()) || (this
						.getKodeFasilitas() != null
						&& castOther.getKodeFasilitas() != null && this
						.getKodeFasilitas()
						.equals(castOther.getKodeFasilitas())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getKodeOutlet() == null ? 0 : this.getKodeOutlet()
						.hashCode());
		result = 37
				* result
				+ (getKodeFasilitas() == null ? 0 : this.getKodeFasilitas()
						.hashCode());
		return result;
	}

}
