package id.qsolution.models;

// Generated Jan 29, 2014 12:26:12 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
/**
 * TmPeriodeSurvey generated by hbm2java
 */
@SuppressWarnings("serial")

public class TmPeriodeSurvey implements java.io.Serializable {

	private TmPeriodeSurveyId id;
	private Date tglMulai;
	private Date tglSelesai;

	public TmPeriodeSurvey() {
	}

	public TmPeriodeSurvey(TmPeriodeSurveyId id) {
		this.id = id;
	}

	public TmPeriodeSurvey(TmPeriodeSurveyId id, Date tglMulai, Date tglSelesai) {
		this.id = id;
		this.tglMulai = tglMulai;
		this.tglSelesai = tglSelesai;
	}


	public TmPeriodeSurveyId getId() {
		return this.id;
	}

	public void setId(TmPeriodeSurveyId id) {
		this.id = id;
	}

	public Date getTglMulai() {
		return this.tglMulai;
	}

	public void setTglMulai(Date tglMulai) {
		this.tglMulai = tglMulai;
	}


	public Date getTglSelesai() {
		return this.tglSelesai;
	}

	public void setTglSelesai(Date tglSelesai) {
		this.tglSelesai = tglSelesai;
	}

}
