package id.qsolution.models;

// Generated Jan 29, 2014 12:26:12 AM by Hibernate Tools 3.4.0.CR1

import java.util.Set;
/**
 * TmPropinsi generated by hbm2java
 */
@SuppressWarnings("serial")
public class TmPropinsi implements java.io.Serializable {

	private String kode;
	private String nama;
	//private Set<TmKabupaten> tmKabupatens = new HashSet<TmKabupaten>(0);

	public TmPropinsi() {
	}

	public TmPropinsi(String kode) {
		this.kode = kode;
	}

	public TmPropinsi(String kode, String nama, Set<TmKabupaten> tmKabupatens) {
		this.kode = kode;
		this.nama = nama;
		//this.tmKabupatens = tmKabupatens;
	}

	public String getKode() {
		return this.kode;
	}

	public void setKode(String kode) {
		this.kode = kode;
	}

	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "tmPropinsi")
	public Set<TmKabupaten> getTmKabupatens() {
		return this.tmKabupatens;
	}

	public void setTmKabupatens(Set<TmKabupaten> tmKabupatens) {
		this.tmKabupatens = tmKabupatens;
	}*/

}
