package id.qsolution.models;

import com.turbomanage.storm.api.Entity;
import com.turbomanage.storm.api.Id;

// Generated Jan 30, 2014 10:07:18 PM by Hibernate Tools 3.4.0.CR1


/**
 * TmPromosiSku generated by hbm2java
 */

@SuppressWarnings("serial")
@Entity
public class TmPromosiSku implements java.io.Serializable {

	@Id
	private long id;
	private String kode;
	private String nama;
	private String namaSku;
	
	public String getNamaSku() {
		return namaSku;
	}

	public void setNamaSku(String namaSku) {
		this.namaSku = namaSku;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}
	public TmPromosiSku() {
	}

	public TmPromosiSku(String kode) {
		this.kode = kode;
	}

	public TmPromosiSku(String kode, String nama) {
		this.kode = kode;
		this.nama = nama;
	}

	public String getKode() {
		return this.kode;
	}

	public void setKode(String kode) {
		this.kode = kode;
	}

	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

}
