package id.qsolution.models;

import com.turbomanage.storm.api.Entity;
import com.turbomanage.storm.api.Id;

// Generated Jan 30, 2014 10:07:18 PM by Hibernate Tools 3.4.0.CR1



/**
 * TmSku generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
public class TmSku implements java.io.Serializable {

	
	@Id
	private long id;
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	private String kode;
	private String kodeBrand;
	private String deskripsi;
	private String kodeSubKategori;
	private String kodeVarian;
	private String kodePackage;
	private String kodeVolum;


	public String getKodeSubKategori() {
		return kodeSubKategori;
	}

	public void setKodeSubKategori(String kodeSubKategori) {
		this.kodeSubKategori = kodeSubKategori;
	}


	public String getKodeVarian() {
		return kodeVarian;
	}

	public void setKodeVarian(String kodeVarian) {
		this.kodeVarian = kodeVarian;
	}

	
	public String getKodePackage() {
		return kodePackage;
	}

	public void setKodePackage(String kodePackage) {
		this.kodePackage = kodePackage;
	}


	public String getKodeVolum() {
		return kodeVolum;
	}

	public void setKodeVolum(String kodeVolum) {
		this.kodeVolum = kodeVolum;
	}


	public TmSku() {
	}

	public TmSku(String kode) {
		this.kode = kode;
	}

	public TmSku(String kode, TmUnit tmUnit, TmVarian tmVarian,
			String kodeBrand, String deskripsi) {
		this.kode = kode;
	/*	this.tmUnit = tmUnit;
		this.tmVarian = tmVarian;*/
		this.kodeBrand = kodeBrand;
		this.deskripsi = deskripsi;
	}


	public String getKode() {
		return this.kode;
	}

	public void setKode(String kode) {
		this.kode = kode;
	}


	public String getKodeBrand() {
		return this.kodeBrand;
	}

	public void setKodeBrand(String kodeBrand) {
		this.kodeBrand = kodeBrand;
	}

	public String getDeskripsi() {
		return this.deskripsi;
	}

	public void setDeskripsi(String deskripsi) {
		this.deskripsi = deskripsi;
	}

}
