package id.qsolution.models;

import com.turbomanage.storm.api.Entity;
import com.turbomanage.storm.api.Id;

// Generated Jan 29, 2014 12:26:12 AM by Hibernate Tools 3.4.0.CR1


/**
 * TmStatusBangunan generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
public class TmStatusBangunan implements java.io.Serializable {

	@Id
	private long id;
	private String kode;
	private String name;

	public TmStatusBangunan() {
	}

	public TmStatusBangunan(String kode) {
		this.kode = kode;
	}

	public TmStatusBangunan(String kode, String name) {
		this.kode = kode;
		this.name = name;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}
	
	public String getKode() {
		return this.kode;
	}

	public void setKode(String kode) {
		this.kode = kode;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
