package id.qsolution.models;

// Generated Jan 29, 2014 12:26:12 AM by Hibernate Tools 3.4.0.CR1

import java.util.Set;
import com.turbomanage.storm.api.Entity;
import com.turbomanage.storm.api.Id;
/**
 * TmStatusKunjungan generated by hbm2java
 */
@Entity
@SuppressWarnings("serial")
public class TmStatusKunjungan implements java.io.Serializable {

	@Id
	private long id;
	private String kode;
	private String nama;
	//private Set<TtMKunjunganSurveyor> ttMKunjunganSurveyors = new HashSet<TtMKunjunganSurveyor>(
	//		0);

	public TmStatusKunjungan() {
	}

	public TmStatusKunjungan(String kode) {
		this.kode = kode;
	}

	public TmStatusKunjungan(String kode, String nama,
			Set<TtMKunjunganSurveyor> ttMKunjunganSurveyors) {
		this.kode = kode;
		this.nama = nama;
//		this.ttMKunjunganSurveyors = ttMKunjunganSurveyors;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}
	public String getKode() {
		return this.kode;
	}

	public void setKode(String kode) {
		this.kode = kode;
	}

	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}
	
	@Override
	public String toString() {
		
		return nama;
	}

	/*public Set<TtMKunjunganSurveyor> getTtMKunjunganSurveyors() {
		return this.ttMKunjunganSurveyors;
	}

	public void setTtMKunjunganSurveyors(
			Set<TtMKunjunganSurveyor> ttMKunjunganSurveyors) {
		this.ttMKunjunganSurveyors = ttMKunjunganSurveyors;
	}*/

}
