package id.qsolution.models;

import com.turbomanage.storm.api.Entity;
import com.turbomanage.storm.api.Id;

// Generated Jan 29, 2014 12:26:12 AM by Hibernate Tools 3.4.0.CR1


/**
 * TmSubKategoriBarang generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
public class TmSubKategoriBarang implements java.io.Serializable {
	@Id
	private long id;
	public long getId() {
		return id;
	}
	public void setId(long id) {
		this.id = id;
	}
	public String getKode() {
		return kode;
	}
	public void setKode(String kode) {
		this.kode = kode;
	}
	public String getNama() {
		return nama;
	}
	public void setNama(String nama) {
		this.nama = nama;
	}
	public String getKode_kategori() {
		return kode_kategori;
	}
	public void setKode_kategori(String kode_kategori) {
		this.kode_kategori = kode_kategori;
	}
	private String kode;
	private String nama;
	private String kode_kategori;

	
}
