package id.qsolution.models;

import com.turbomanage.storm.api.Entity;
import com.turbomanage.storm.api.Id;

// Generated Jan 30, 2014 10:07:18 PM by Hibernate Tools 3.4.0.CR1

/**
 * TmSumberProduk generated by hbm2java
 */
@Entity
@SuppressWarnings("serial")
public class TmSumberProduk implements java.io.Serializable {


	@Id
	private long id;
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	private String kode;
	private String nama;

	public TmSumberProduk() {
	}

	public TmSumberProduk(String kode) {
		this.kode = kode;
	}

	public TmSumberProduk(String kode, String nama) {
		this.kode = kode;
		this.nama = nama;
	}

	public String getKode() {
		return this.kode;
	}

	public void setKode(String kode) {
		this.kode = kode;
	}

	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

}
