package id.qsolution.models;

import com.turbomanage.storm.api.Entity;
import com.turbomanage.storm.api.Id;

// Generated Jan 29, 2014 12:26:12 AM by Hibernate Tools 3.4.0.CR1



/**
 * TmTipeOutlet generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
public class TmTipeOutlet implements java.io.Serializable {

	@Id
	private long id;
	private String kode;
	private String nama;
	//private Set<TmGroupRak> tmGroupRaks = new HashSet<TmGroupRak>(0);
	//private Set<TmFasilitas> tmFasilitases = new HashSet<TmFasilitas>(0);

	public TmTipeOutlet() {
	}

	public TmTipeOutlet(String kode) {
		this.kode = kode;
	}
/*
	public TmTipeOutlet(String kode, String nama, Set<TmGroupRak> tmGroupRaks,
			Set<TmFasilitas> tmFasilitases) {
		this.kode = kode;
		this.nama = nama;
		//this.tmGroupRaks = tmGroupRaks;
		//this.tmFasilitases = tmFasilitases;
	}*/

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getKode() {
		return this.kode;
	}

	public void setKode(String kode) {
		this.kode = kode;
	}

	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "tmTipeOutlet")
	public Set<TmGroupRak> getTmGroupRaks() {
		return this.tmGroupRaks;
	}

	public void setTmGroupRaks(Set<TmGroupRak> tmGroupRaks) {
		this.tmGroupRaks = tmGroupRaks;
	}
*/
/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tmTipeOutlet")
	public Set<TmFasilitas> getTmFasilitases() {
		return this.tmFasilitases;
	}

	public void setTmFasilitases(Set<TmFasilitas> tmFasilitases) {
		this.tmFasilitases = tmFasilitases;
	}
*/
}
