package id.qsolution.models;

// Generated Jan 29, 2014 12:26:12 AM by Hibernate Tools 3.4.0.CR1


/**
 * TtDaftarOutletSurveyId generated by hbm2java
 */
@SuppressWarnings("serial")
public class TtDaftarOutletSurveyId implements java.io.Serializable {

	private String kodeOutlet;
	private String kodeSurveyor;
	private String periodeMulai;
	private String periodeSelesai;

	public TtDaftarOutletSurveyId() {
	}

	public TtDaftarOutletSurveyId(String kodeOutlet, String kodeSurveyor,
			String periodeMulai, String periodeSelesai) {
		this.kodeOutlet = kodeOutlet;
		this.kodeSurveyor = kodeSurveyor;
		this.periodeMulai = periodeMulai;
		this.periodeSelesai = periodeSelesai;
	}
	public String getKodeOutlet() {
		return this.kodeOutlet;
	}

	public void setKodeOutlet(String kodeOutlet) {
		this.kodeOutlet = kodeOutlet;
	}

	public String getKodeSurveyor() {
		return this.kodeSurveyor;
	}

	public void setKodeSurveyor(String kodeSurveyor) {
		this.kodeSurveyor = kodeSurveyor;
	}

	public String getPeriodeMulai() {
		return this.periodeMulai;
	}

	public void setPeriodeMulai(String periodeMulai) {
		this.periodeMulai = periodeMulai;
	}

	public String getPeriodeSelesai() {
		return this.periodeSelesai;
	}

	public void setPeriodeSelesai(String periodeSelesai) {
		this.periodeSelesai = periodeSelesai;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TtDaftarOutletSurveyId))
			return false;
		TtDaftarOutletSurveyId castOther = (TtDaftarOutletSurveyId) other;

		return ((this.getKodeOutlet() == castOther.getKodeOutlet()) || (this
				.getKodeOutlet() != null && castOther.getKodeOutlet() != null && this
				.getKodeOutlet().equals(castOther.getKodeOutlet())))
				&& ((this.getKodeSurveyor() == castOther.getKodeSurveyor()) || (this
						.getKodeSurveyor() != null
						&& castOther.getKodeSurveyor() != null && this
						.getKodeSurveyor().equals(castOther.getKodeSurveyor())))
				&& ((this.getPeriodeMulai() == castOther.getPeriodeMulai()) || (this
						.getPeriodeMulai() != null
						&& castOther.getPeriodeMulai() != null && this
						.getPeriodeMulai().equals(castOther.getPeriodeMulai())))
				&& ((this.getPeriodeSelesai() == castOther.getPeriodeSelesai()) || (this
						.getPeriodeSelesai() != null
						&& castOther.getPeriodeSelesai() != null && this
						.getPeriodeSelesai().equals(
								castOther.getPeriodeSelesai())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getKodeOutlet() == null ? 0 : this.getKodeOutlet()
						.hashCode());
		result = 37
				* result
				+ (getKodeSurveyor() == null ? 0 : this.getKodeSurveyor()
						.hashCode());
		result = 37
				* result
				+ (getPeriodeMulai() == null ? 0 : this.getPeriodeMulai()
						.hashCode());
		result = 37
				* result
				+ (getPeriodeSelesai() == null ? 0 : this.getPeriodeSelesai()
						.hashCode());
		return result;
	}

}
