package id.qsolution.models;

// Generated Jan 29, 2014 12:26:12 AM by Hibernate Tools 3.4.0.CR1


/**
 * TtDKunjunganSurveyorRakPosmId generated by hbm2java
 */
@SuppressWarnings("serial")

public class TtDKunjunganSurveyorRakPosmId implements java.io.Serializable {

	private String kodeKunjungan;
	private String nomorUrut;
	private String kodeBrand;
	private String kodePosm;

	public TtDKunjunganSurveyorRakPosmId() {
	}

	public TtDKunjunganSurveyorRakPosmId(String kodeKunjungan,
			String nomorUrut, String kodeBrand, String kodePosm) {
		this.kodeKunjungan = kodeKunjungan;
		this.nomorUrut = nomorUrut;
		this.kodeBrand = kodeBrand;
		this.kodePosm = kodePosm;
	}

	public String getKodeKunjungan() {
		return this.kodeKunjungan;
	}

	public void setKodeKunjungan(String kodeKunjungan) {
		this.kodeKunjungan = kodeKunjungan;
	}

	public String getNomorUrut() {
		return this.nomorUrut;
	}

	public void setNomorUrut(String nomorUrut) {
		this.nomorUrut = nomorUrut;
	}

	public String getKodeBrand() {
		return this.kodeBrand;
	}

	public void setKodeBrand(String kodeBrand) {
		this.kodeBrand = kodeBrand;
	}

	public String getKodePosm() {
		return this.kodePosm;
	}

	public void setKodePosm(String kodePosm) {
		this.kodePosm = kodePosm;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TtDKunjunganSurveyorRakPosmId))
			return false;
		TtDKunjunganSurveyorRakPosmId castOther = (TtDKunjunganSurveyorRakPosmId) other;

		return ((this.getKodeKunjungan() == castOther.getKodeKunjungan()) || (this
				.getKodeKunjungan() != null
				&& castOther.getKodeKunjungan() != null && this
				.getKodeKunjungan().equals(castOther.getKodeKunjungan())))
				&& ((this.getNomorUrut() == castOther.getNomorUrut()) || (this
						.getNomorUrut() != null
						&& castOther.getNomorUrut() != null && this
						.getNomorUrut().equals(castOther.getNomorUrut())))
				&& ((this.getKodeBrand() == castOther.getKodeBrand()) || (this
						.getKodeBrand() != null
						&& castOther.getKodeBrand() != null && this
						.getKodeBrand().equals(castOther.getKodeBrand())))
				&& ((this.getKodePosm() == castOther.getKodePosm()) || (this
						.getKodePosm() != null
						&& castOther.getKodePosm() != null && this
						.getKodePosm().equals(castOther.getKodePosm())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getKodeKunjungan() == null ? 0 : this.getKodeKunjungan()
						.hashCode());
		result = 37 * result
				+ (getNomorUrut() == null ? 0 : this.getNomorUrut().hashCode());
		result = 37 * result
				+ (getKodeBrand() == null ? 0 : this.getKodeBrand().hashCode());
		result = 37 * result
				+ (getKodePosm() == null ? 0 : this.getKodePosm().hashCode());
		return result;
	}

}
