package id.qsolution.models;

import com.turbomanage.storm.api.Entity;
import com.turbomanage.storm.api.Id;

// Generated Jan 29, 2014 12:26:12 AM by Hibernate Tools 3.4.0.CR1


/**
 * TtDKunjunganSurveyorRakSkuPromosi generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
public class TtDKunjunganSurveyorRakSkuPromosi implements java.io.Serializable {

	@Id
	private long id;
	private String kodeKunjungan;
	private String nomorUrut;
	private String kodeSku;
	private String kodePromosi;
	private String deskripsi;
	private String kode;
	
	private String namaSku;
	public String getNamaSku() {
		return namaSku;
	}
	public void setNamaSku(String namaSku) {
		this.namaSku = namaSku;
	}
	public String getNamaPromosi() {
		return namaPromosi;
	}
	public void setNamaPromosi(String namaPromosi) {
		this.namaPromosi = namaPromosi;
	}
	private String namaPromosi;

	public String getKode() {
		return kode;
	}
	public void setKode(String kode) {
		this.kode = kode;
	}
	public long getId() {
		return id;
	}
	public void setId(long id) {
		this.id = id;
	}
	public String getKodeKunjungan() {
		return kodeKunjungan;
	}
	public void setKodeKunjungan(String kodeKunjungan) {
		this.kodeKunjungan = kodeKunjungan;
	}
	public String getNomorUrut() {
		return nomorUrut;
	}
	public void setNomorUrut(String nomorUrut) {
		this.nomorUrut = nomorUrut;
	}
	public String getKodeSku() {
		return kodeSku;
	}
	public void setKodeSku(String kodeSku) {
		this.kodeSku = kodeSku;
	}
	public String getKodePromosi() {
		return kodePromosi;
	}
	public void setKodePromosi(String kodePromosi) {
		this.kodePromosi = kodePromosi;
	}
	public String getDeskripsi() {
		return deskripsi;
	}
	public void setDeskripsi(String deskripsi) {
		this.deskripsi = deskripsi;
	}
	

}
