package id.qsolution.models;

// Generated Jan 29, 2014 12:26:12 AM by Hibernate Tools 3.4.0.CR1

/**
 * TtDKunjunganSurveyorRakSkuPromosiId generated by hbm2java
 */
@SuppressWarnings("serial")
public class TtDKunjunganSurveyorRakSkuPromosiId implements
		java.io.Serializable {

	private String kodeKunjungan;
	private String nomorUrut;
	private String kodeSku;
	private String kodePromosi;

	public TtDKunjunganSurveyorRakSkuPromosiId() {
	}

	public TtDKunjunganSurveyorRakSkuPromosiId(String kodeKunjungan,
			String nomorUrut, String kodeSku, String kodePromosi) {
		this.kodeKunjungan = kodeKunjungan;
		this.nomorUrut = nomorUrut;
		this.kodeSku = kodeSku;
		this.kodePromosi = kodePromosi;
	}

	public String getKodeKunjungan() {
		return this.kodeKunjungan;
	}

	public void setKodeKunjungan(String kodeKunjungan) {
		this.kodeKunjungan = kodeKunjungan;
	}

	public String getNomorUrut() {
		return this.nomorUrut;
	}

	public void setNomorUrut(String nomorUrut) {
		this.nomorUrut = nomorUrut;
	}

	public String getKodeSku() {
		return this.kodeSku;
	}

	public void setKodeSku(String kodeSku) {
		this.kodeSku = kodeSku;
	}

	public String getKodePromosi() {
		return this.kodePromosi;
	}

	public void setKodePromosi(String kodePromosi) {
		this.kodePromosi = kodePromosi;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TtDKunjunganSurveyorRakSkuPromosiId))
			return false;
		TtDKunjunganSurveyorRakSkuPromosiId castOther = (TtDKunjunganSurveyorRakSkuPromosiId) other;

		return ((this.getKodeKunjungan() == castOther.getKodeKunjungan()) || (this
				.getKodeKunjungan() != null
				&& castOther.getKodeKunjungan() != null && this
				.getKodeKunjungan().equals(castOther.getKodeKunjungan())))
				&& ((this.getNomorUrut() == castOther.getNomorUrut()) || (this
						.getNomorUrut() != null
						&& castOther.getNomorUrut() != null && this
						.getNomorUrut().equals(castOther.getNomorUrut())))
				&& ((this.getKodeSku() == castOther.getKodeSku()) || (this
						.getKodeSku() != null && castOther.getKodeSku() != null && this
						.getKodeSku().equals(castOther.getKodeSku())))
				&& ((this.getKodePromosi() == castOther.getKodePromosi()) || (this
						.getKodePromosi() != null
						&& castOther.getKodePromosi() != null && this
						.getKodePromosi().equals(castOther.getKodePromosi())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getKodeKunjungan() == null ? 0 : this.getKodeKunjungan()
						.hashCode());
		result = 37 * result
				+ (getNomorUrut() == null ? 0 : this.getNomorUrut().hashCode());
		result = 37 * result
				+ (getKodeSku() == null ? 0 : this.getKodeSku().hashCode());
		result = 37
				* result
				+ (getKodePromosi() == null ? 0 : this.getKodePromosi()
						.hashCode());
		return result;
	}

}
