package id.qsolution.models;

// Generated Jan 29, 2014 12:26:12 AM by Hibernate Tools 3.4.0.CR1


/**
 * TtDKunjunganSurveyorRakId generated by hbm2java
 */
@SuppressWarnings("serial")

public class TtDKunjunganSurveyorRakId implements java.io.Serializable {

	private String kodeKunjungan;
	private String nomorUrut;

	public TtDKunjunganSurveyorRakId() {
	}

	public TtDKunjunganSurveyorRakId(String kodeKunjungan, String nomorUrut) {
		this.kodeKunjungan = kodeKunjungan;
		this.nomorUrut = nomorUrut;
	}

	public String getKodeKunjungan() {
		return this.kodeKunjungan;
	}

	public void setKodeKunjungan(String kodeKunjungan) {
		this.kodeKunjungan = kodeKunjungan;
	}

	public String getNomorUrut() {
		return this.nomorUrut;
	}

	public void setNomorUrut(String nomorUrut) {
		this.nomorUrut = nomorUrut;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TtDKunjunganSurveyorRakId))
			return false;
		TtDKunjunganSurveyorRakId castOther = (TtDKunjunganSurveyorRakId) other;

		return ((this.getKodeKunjungan() == castOther.getKodeKunjungan()) || (this
				.getKodeKunjungan() != null
				&& castOther.getKodeKunjungan() != null && this
				.getKodeKunjungan().equals(castOther.getKodeKunjungan())))
				&& ((this.getNomorUrut() == castOther.getNomorUrut()) || (this
						.getNomorUrut() != null
						&& castOther.getNomorUrut() != null && this
						.getNomorUrut().equals(castOther.getNomorUrut())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getKodeKunjungan() == null ? 0 : this.getKodeKunjungan()
						.hashCode());
		result = 37 * result
				+ (getNomorUrut() == null ? 0 : this.getNomorUrut().hashCode());
		return result;
	}

}
