package id.qsolution.models;

import com.turbomanage.storm.api.Entity;
import com.turbomanage.storm.api.Id;

// Generated Jan 29, 2014 12:26:12 AM by Hibernate Tools 3.4.0.CR1
/**
 * TtPhoto generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
public class TtPhotoRak implements java.io.Serializable {

	@Id
	private long id;
	private String kode;
	private String kodeKategori;
	private String kodeOutlet;
	private String kodeRak;
	private String nama;
	private String namaFoto;
	private String deskripsi;
	private String status;
	
	public long getId() {
		return id;
	}
	public void setId(long id) {
		this.id = id;
	}
	public String getKode() {
		return kode;
	}
	public void setKode(String kode) {
		this.kode = kode;
	}
	public String getKodeKategori() {
		return kodeKategori;
	}
	public void setKodeKategori(String kodeKategori) {
		this.kodeKategori = kodeKategori;
	}
	
	public String getKodeRak() {
		return kodeRak;
	}
	public void setKodeRak(String kodeRak) {
		this.kodeRak = kodeRak;
	}
	public String getKodeOutlet() {
		return kodeOutlet;
	}
	public void setKodeOutlet(String kodeOutlet) {
		this.kodeOutlet = kodeOutlet;
	}
	public String getNama() {
		return nama;
	}
	public void setNama(String nama) {
		this.nama = nama;
	}
	public String getNamaFoto() {
		return namaFoto;
	}
	public void setNamaFoto(String namaFoto) {
		this.namaFoto = namaFoto;
	}
	public String getDeskripsi() {
		return deskripsi;
	}
	public void setDeskripsi(String deskripsi) {
		this.deskripsi = deskripsi;
	}
	
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	
	@Override
	public String toString() {
		return this.getKodeRak() +"/R."+this.getNama()+"/"+this.getDeskripsi();
	}
}
