package id.qsolution.models;

import com.turbomanage.storm.api.Entity;
import com.turbomanage.storm.api.Id;

// Generated Jan 29, 2014 12:26:12 AM by Hibernate Tools 3.4.0.CR1
/**
 * TtPhoto generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
public class TtPhoto implements java.io.Serializable {

	@Id
	private long id;
	private String kode;
	private String kode_outlet;
	private String nama;
	private String deskripsi;
	private String status;


	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	public long getId() {
		return id;
	}
	public void setId(long id) {
		this.id = id;
	}
	public String getKode() {
		return kode;
	}
	public void setKode(String kode) {
		this.kode = kode;
	}
	public String getKode_outlet() {
		return kode_outlet;
	}
	public void setKode_outlet(String kode_outlet) {
		this.kode_outlet = kode_outlet;
	}
	public String getNama() {
		return nama;
	}
	public void setNama(String nama) {
		this.nama = nama;
	}
	public String getDeskripsi() {
		return deskripsi;
	}
	public void setDeskripsi(String deskripsi) {
		this.deskripsi = deskripsi;
	}
	
	@Override
	public String toString() {
		return kode_outlet +"\n"+deskripsi;
	}
	
}
